### ISSUE TITLE
What is the license of this repository?

### ISSUE THREAD

**Issue by matkoniecz** [clarisma/geodesk-site#11]
footer has "© 2023 GeoDesk" with no mention of license so looks like fully copyrighted

https://github.com/clarisma/geodesk-site has https://github.com/clarisma/geodesk-site/blob/main/NOTICE with

> Website and contents (C) 2022 GeoDesk.

also suggesting fully copyrighted and a bit confusing "The original work is licensed as follows"

Is all original work including work by GeoDesk licensed under MIT? If yes, then which parts are not MIT?

Is it proprietary source with original code (which one?) still MIT licensed and source code is published without open-sourcing it? If yes, how people can distinguish MIT-parts and fully copyrighted parts?

There is 

https://github.com/clarisma/geodesk-site/blob/4886e0ea722edc62cce10be35d2aacd23a766b22/index.html#L135

suggesting in turn that documentation is also freely-licenced.

**Comment by clarisma** [comment]
The GeoDesk website currently isn't licensed to the public. The design is based on a CloudCannon template (the "original work"), which is published under an MIT license.
It would make sense to open-source at least the documentation portion of the website. We haven't decided yet whether to use a Create Commons license or Apache 2.0. We will address this as part of the revisions for Version 0.2, which we aim to release this spring.
The software itself is licensed under Apache 2.0 (database engine) and AGPL 3.0 (command-line utility).
