### ISSUE TITLE
https://docs.geodesk.com/why-geodesk is not mentioning open source

### ISSUE THREAD

**Issue by matkoniecz** [clarisma/geodesk-site#4]
https://docs.geodesk.com/why-geodesk is not mentioning at all that geodesk is open source, and it seems to be

To find https://github.com/clarisma/gol-tool/ I needed to go to https://wiki.openstreetmap.org/wiki/GeoDesk then https://github.com/clarisma/geodesk-examples then https://github.com/clarisma then https://github.com/clarisma?tab=repositories then https://github.com/clarisma/gol-tool/

Unless https://github.com/clarisma/gol-tool/ contains only stubs to proprietary binary blobs and is "open source" not open source like some projects?

**Comment by clarisma** [comment]
Thanks, I've clarified this in the documentation.

All of GeoDesk is open-source. The database engine is released under an Apache license (a permissive license that enables it to be included in closed-source projects, as well); the GOL command-line utility is AGPL (a more traditional copyleft license that ensures that any forks will stay open).

**Comment by matkoniecz** [comment]
Adding this "fully open source" also to https://github.com/clarisma/geodesk-docs#why-geodesk may make sense (and yes, just because something is in public repo does not make it fully open source - people close to me had obnoxious issue with project only pretending to be open source, so reassuring people may be useful even in repo itself)
